language: java
jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
    - tech_msy@woowahan.com
    - tech_syl@woowahan.com
    - tech_hjl@woowahan.com
    - tech_syk@woowahan.com
    - tech_jiwoo@woowahan.com